# FILE: .\configs\domain_definitions.yaml
# ==============================================================================
# PART 1: PHYSICAL PROBLEM DEFINITION
# ==============================================================================
# This file contains the "What": Geometry, Loads, BCs, and Materials.


# ------------------------------------------------------------------------------
# GEOMETRY DEFINITION
# ------------------------------------------------------------------------------
geometry:
  length_x: 80
  length_y: 20
  length_z: 10
  sphere1:
    type: sphere
    center: [12.51, 28.49, 50]
    diameter: 8
    properties:
      stiffness_ratio: 0
      specific_mass: 0
      thermal_expansion: 0
  sphere2:
    type: sphere
    center: [60.38, -0.07, 50]
    diameter: 4
    properties:
      stiffness_ratio: 10
      specific_mass: 0
      thermal_expansion: 0.000012
  sphere3:
    type: sphere
    center: [34.29, 5, 50]
    diameter: 4
    properties:
      stiffness_ratio: 1
      specific_mass: 0
      thermal_expansion: 0.0002
  box1:
    type: box
    center: [40, 11.83, 5.01]
    size: [90, 5, 8.9]
    properties:
      stiffness_ratio: 0
      specific_mass: 0
      thermal_expansion: 0
  box2:
    type: box
    center: [40, 9, 5]
    size: [90, 0.6, 12]
    properties:
      stiffness_ratio: .01
      specific_mass: 0.015
      thermal_expansion: 0

# ------------------------------------------------------------------------------
# BOUNDARY CONDITIONS
# ------------------------------------------------------------------------------
boundary_conditions:
  - location: [0%, 30%, ':']
    DoFs: [1, 2, 3]
  - location: [100%, 30%, ':']
    DoFs: [2, 3]

# ------------------------------------------------------------------------------
# EXTERNAL FORCES
# ------------------------------------------------------------------------------
external_forces:
  - name: Y10
    location: [80, 0, 0]
    F: [0, 0.00001, 0]
  - name: Z-10
    location: [40, 9, 5]
    F: [0, 0, -0.0010]
  - name: Y20
    location: [80, 0, 10]
    F: [0, 0.00002, 0]
  - name: Mid_Y20
    location: [40, 0, 5]
    F: [0, 0.000015, 0]

# ------------------------------------------------------------------------------
# MATERIAL PROPERTIES
# ------------------------------------------------------------------------------
material:
  E: 1
  nu: 0.3
  material_density: 0.00
  gravity_acceleration: 10
  delta_temperature: 0
  l1_stress_allowable_tension: 2
  l1_stress_allowable_compression: 1.5
 
