# FILE: .\configs\domain_definitions.yaml
# ==============================================================================
# PART 1: PHYSICAL PROBLEM DEFINITION
# ==============================================================================
# This file contains the "What": Geometry, Loads, BCs, and Materials.


# ------------------------------------------------------------------------------
# GEOMETRY DEFINITION
# ------------------------------------------------------------------------------
geometry:
  length_x: 60
  length_y: 40
  length_z: 10
  sphere1:
    type: sphere
    center: [12.51, 28.49, 7.45]
    diameter: 8
    stiffness_ratio: 0
  sphere2:
    type: sphere
    center: [38.87, 11.72, 1.88]
    diameter: 12
    stiffness_ratio: 10
  sphere3:
    type: sphere
    center: [22.52, 5, -2.37]
    diameter: 4
    stiffness_ratio: -10
  box1:
    type: box
    center: [28, 15, 7.07]
    size: [1, 2, 3]
    stiffness_ratio: 5
  box2:
    type: box
    center: [45.06, 8.95, 9.94]
    size: [12, 11, 2]
    stiffness_ratio: 0

# ------------------------------------------------------------------------------
# BOUNDARY CONDITIONS
# ------------------------------------------------------------------------------
boundary_conditions:
  - location: [0, ':', ':']
    DoFs: [1, 3]
  - location: [100%, 0%, ':']
    DoFs: [1, 2, 3]

# ------------------------------------------------------------------------------
# EXTERNAL FORCES
# ------------------------------------------------------------------------------
external_forces:
  - name: Mid_Y20
    location: [3, 40, 5]
    F: [0, -15, 0]

# ------------------------------------------------------------------------------
# MATERIAL PROPERTIES
# ------------------------------------------------------------------------------
material:
  E: 1
  nu: 0.3
  material_density: 0.001
  gravity_acceleration: 9.81
  delta_temperature: 0
  l1_stress_allowable: 1.5
